### ISSUE TITLE
Unable to start new job

### ISSUE THREAD

**Issue by jasperla** [Strider-CD/strider-cli#10]
I'm running Strider 1.6.3 and have version 1.4.2 of this plugin:

```
strider@2b17281484e5:~$ /usr/local/bin/strider runTest -l admin@example.org -p 5ecre7 --project project/name
Error: Repo was not found
strider@2b17281484e5:~$
```

When I manually do a curl(1):
```
$ curl -d "email=admin@example.org&password=5ecre7" http://localhost:3000/api/session
{"projects":[{"access_level":2,"display_name":"project/name","name":"project/name","_id":"54d2757fe0f2131200099dbb"}]}
$
```

Which clearly shows the `project/name` as being a valid project. Is there any way I could help to debug this issue?

**Comment by knownasilya** [comment]
@jasperla were you able to solve this issue?

**Comment by jasperla** [comment]
Hi, I haven't. And actually I didn't pursue getting it working and moved on.. So unless someone else ran into this I think it should be closed.

**Comment by knownasilya** [comment]
@jasperla thanks for getting back, and sorry I couldn't help when you needed it.
