### ISSUE TITLE
Handle plugins with prepublish scripts

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/strider-cli#12]
Se here: https://github.com/Strider-CD/strider-email-notifier/blob/master/package.json#L15

there is a prepublish script, but it can't find the dev dependency 'istanbul' since it's not installed? Maybe we should use `--ignore-scripts` flag for `npm install`?

cc @keyvanfatehi

**Comment by oliversalzburg** [comment]
Very good idea, I was just about to suggest this. I have istanbul installed, but it can not be invoked in the default way on Windows. Thus, installation of said plugin fails in an unexpected way.

Either way, there is really no point to run unit tests or whatever when installing a plugin.

I vote for `npm install --ignore-scripts`, maybe with the addition to have a flag in the ecosystem index when a plugin *requires* scripts to run.

**Comment by knownasilya** [comment]
Will take a PR.

**Comment by oliversalzburg** [comment]
I haven't looked at the ecosystem stuff yet. I'll try to submit something once I have a better understanding.
