### ISSUE TITLE
Redirect to wrong callback URL when authenticating via GitHub

### ISSUE THREAD

**Issue by wolfika** [Strider-CD/strider-cli#19]
I'm trying to connect my Strider account to my GitHub account.

![Screenshot](http://puu.sh/kia41/dd061fcc5f.png)

After clicking the button, I'm taken to GitHub to authorize the request, which I do, and then I'm redirected to `http://localhost:3000/auth/github/callback?code=#MY_CODE_HERE#`. My Strider deploy is not running on this address, not even on port 3000, so basically I can't get it to link my GitHub account.

*Note*: I could probably try and hack my way through the code, but this is the default behaviour, and if it's broken, it needs to be fixed.

**Comment by knownasilya** [comment]
Did you follow the instructions here first https://github.com/Strider-CD/strider-github#required-configuration?

**Comment by wolfika** [comment]
Oh, it appears this must have slipped my attention. I thought the env variables listed in the main repo's README was all I needed. And I just realized I opened this issue in the wrong repo... Sorry for this dumb move, feel free to close this. Thanks!
