### ISSUE TITLE
run() missing arguments

### ISSUE THREAD

**Issue by shaunc** [Strider-CD/strider-cli#8]
When I run "strider runTest" I get "ReferenceError: email is not defined" in run.js line 12.

It would seem that parameters are not being threaded through from runTest() -- should they go in runOpts?

This seems like such an obvious error that I worry I'm missing something. Is strider-cli... um... working? Is it in the process of being split from strider itself, maybe, and that is why its discombobulated? Do you want a pull request that just puts the parameters in runOpts then takes them out in run(), or is there another plan?

While I'm at it, where is the strider server that is running strider tests? :) (And where are the tests?)

**Comment by echiu64** [comment]
Proposed fix... https://github.com/Strider-CD/strider-cli/pull/9

**Comment by knownasilya** [comment]
@keyvanfatehi can you publish 1.4.2?

**Comment by keyvanfatehi** [comment]
~/P/S/strider-cli git:master ❯❯❯ npm publish
+ strider-cli@1.4.2
~/P/S/strider-cli git:master ❯❯❯ npm owner ls strider-cli
keyvanfatehi <keyvanfatehi@gmail.com>
knownasilya <ilya@burstcreations.com>

:+1:

**Comment by knownasilya** [comment]
Ah, good call :smile:
